### ISSUE TITLE
Cannot load huggingface model

### ISSUE THREAD

**Issue by jvence** [MahmoudWahdan/dialog-nlu#21]
Trying to train using https://huggingface.co/deepset/bert-large-uncased-whole-word-masking-squad2

`python3 train_joint_trans.py --train=data/snips/train --val=data/snips/valid --save=saved_models/joint_trans_model --epochs=3 --batch=64 --cache_dir=transformers_cache_dir  --trans=deepset/bert-large-uncased-whole-word-masking-squad2 --from_pt=false`

but I get error:

> Traceback (most recent call last):
>   File "train_joint_trans.py", line 100, in <module>
>     model = create_joint_trans_model(config)
>   File "/Users/aa/dev/project/hoverpin/ai/tensorflow/BERT-Concierge/dialog-nlu/models/trans_auto_model.py", line 65, in create_joint_trans_model
>     model, trans_type = get_transformer_model(pretrained_model_name_or_path, cache_dir, from_pt, layer_pruning)
>   File "/Users/aa/dev/project/hoverpin/ai/tensorflow/BERT-Concierge/dialog-nlu/models/trans_auto_model.py", line 42, in get_transformer_model
>     layer_pruning=layer_pruning)
>   File "/Users/aa/dev/project/hoverpin/ai/tensorflow/BERT-Concierge/dialog-nlu/compression/commons.py", line 384, in from_pretrained
>     return from_pretrained_detailed(model_class, pretrained_model_name_or_path, *model_args, config=config, **kwargs)
>   File "/Users/aa/dev/project/hoverpin/ai/tensorflow/BERT-Concierge/dialog-nlu/compression/commons.py", line 185, in from_pretrained_detailed
>     raise EnvironmentError(msg)
> OSError: Can't load weights for 'deepset/bert-large-uncased-whole-word-masking-squad2'. Make sure that:
> 
> - 'deepset/bert-large-uncased-whole-word-masking-squad2' is a correct model identifier listed on 'https://huggingface.co/models'
> 
> - or 'deepset/bert-large-uncased-whole-word-masking-squad2' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.

**Comment by jvence** [comment]
The reason it fails is because its looking for https://cdn.huggingface.co/deepset/bert-large-uncased-whole-word-masking-squad2/tf_model.h5 which does not exist but pytorch_model.bin DOES exist.

**Comment by jvence** [comment]
Using --from_pt=true resolves issue. Sorry about that.
